<a href="https://colab.research.google.com/github/lokeshchowdary9220/N4si/blob/main/Pandas_and_Titanic_Assesment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Activity 1 Creating Data Frame
import pandas as pd
student ={"Name":["A","B","C","D"],"Age":[12,13,14,15],"Marks": [78,89,96,97]}
df =pd.DataFrame(student)
print(df)

  Name  Age  Marks
0    A   12     78
1    B   13     89
2    C   14     96
3    D   15     97

In [ ]:
#Activity 2 Reading Dataset
from sklearn.datasets import load_iris
iris =load_iris(as_frame=True)
df =iris.frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
#Activity 3 Basic Operations
df.info()

df.describe()

df.shape

df.columns

df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
#Activity 4 Selecting Data
df[["sepal length (cm)", "target"]]
df.iloc[:5]
df.loc[10:20]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
10,5.4,3.7,1.5,0.2,0
11,4.8,3.4,1.6,0.2,0
12,4.8,3.0,1.4,0.1,0
13,4.3,3.0,1.1,0.1,0
14,5.8,4.0,1.2,0.2,0
15,5.7,4.4,1.5,0.4,0
16,5.4,3.9,1.3,0.4,0
17,5.1,3.5,1.4,0.3,0
18,5.7,3.8,1.7,0.3,0
19,5.1,3.8,1.5,0.3,0
20,5.4,3.4,1.7,0.2,0

In [ ]:
#Activity 5 Filtering
df[df["target"]==1]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1
60,5.0,2.0,3.5,1.0,1
61,5.9,3.0,4.2,1.5,1
62,6.0,2.2,4.0,1.0,1
63,6.1,2.9,4.7,1.4,1
64,5.6,2.9,3.6,1.3,1
65,6.7,3.1,4.4,1.4,1
66,5.6,3.0,4.5,1.5,1
67,5.8,2.7,4.1,1.0,1
68,6.2,2.2,4.5,1.5,1
69,5.6,2.5,3.9,1.1,1
70,5.9,3.2,4.8,1.8,1
71,6.1,2.8,4.0,1.3,1
72,6.3,2.5,4.9,1.5,1
73,6.1,2.8,4.7,1.2,1
74,6.4,2.9,4.3,1.3,1
75,6.6,3.0,4.4,1.4,1
76,6.8,2.8,4.8,1.4,1
77,6.7,3.0,5.0,1.7,1
78,6.0,2.9,4.5,1.5,1
79,5.7,2.6,3.5,1.0,1
80,5.5,2.4,3.8,1.1,1
81,5.5,2.4,3.7,1.0,1
82,5.8,2.7,3.9,1.2,1
83,6.0,2.7,5.1,1.6,1
84,5.4,3.0,4.5,1.5,1
85,6.0,3.4,4.5,1.6,1
86,6.7,3.1,4.7,1.5,1
87,6.3,2.3,4.4,1.3,1
88,5.6,3.0,4.1,1.3,1
89,5.5,2.5,4.0,1.3,1
90,5.5,2.6,4.4,1.2,1
91,6.1,3.0,4.6,1.4,1
92,5.8,2.6,4.0,1.2,1
93,5.0,2.3,3.3,1.0,1
94,5.6,2.7,4.2,1.3,1
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1
99,5.7,2.8,4.1,1.3,1

In [ ]:
#Sorting
df.sort_values(by="sepal width (cm)")

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
60,5.0,2.0,3.5,1.0,1
62,6.0,2.2,4.0,1.0,1
119,6.0,2.2,5.0,1.5,2
68,6.2,2.2,4.5,1.5,1
87,6.3,2.3,4.4,1.3,1
...,...,...,...,...,...
5,5.4,3.9,1.7,0.4,0
14,5.8,4.0,1.2,0.2,0
32,5.2,4.1,1.5,0.1,0
33,5.5,4.2,1.4,0.2,0
15,5.7,4.4,1.5,0.4,0

In [7]:
#Assignment
import pandas as pd

df = pd.read_csv("/content/archive.zip")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
#1.Total Passengers ?
print(f"Total passengers are :{len(df["PassengerId"])}")

Total passengers are :891

In [31]:
#2.Average age of Survivors and non Survivors

print(f"Average age of Survivors: {df[df["Survived"]==1]["Age"].mean()}")
print(f"Average age of non survivors: {df[df["Survived"]==0]["Age"].mean()}")

Average age of Survivors: 28.343689655172415
Average age of non survivors: 30.62617924528302

In [54]:
#3.List the Passengers above 60

print(f"Passengers above 60 are:")
for name in df[df['Age']>60]['Name']:
  print(name)

Passengers above 60 are:
Wheadon, Mr. Edward H
Ostby, Mr. Engelhart Cornelius
Goldschmidt, Mr. George B
Connors, Mr. Patrick
Van der hoef, Mr. Wyckoff
Stead, Mr. William Thomas
Andrews, Miss. Kornelia Theodosia
Duane, Mr. Frank
Nysveen, Mr. Johan Hansen
Fortune, Mr. Mark
Millet, Mr. Francis Davis
Turkula, Mrs. (Hedwig)
Artagaveytia, Mr. Ramon
Nicholson, Mr. Arthur Ernest
Wright, Mr. George
Harris, Mr. George
Sutton, Mr. Frederick
Barkworth, Mr. Algernon Henry Wilson
Mitchell, Mr. Henry Michael
Crosby, Capt. Edward Gifford
Stone, Mrs. George Nelson (Martha Evelyn)
Svensson, Mr. Johan

In [66]:

#find the avg fare for each passenger class?
print("Average fare for each passenger class :")
print(df.groupby("Pclass")["Fare"].mean())

Average fare for each passenger class :
Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64